### ISSUE TITLE
Policy support in put_parameter

### ISSUE THREAD

**Issue by ku1ik** [hellogustav/ex_aws_ssm#2]
I'm looking for a way to create Parameter Store parameter with expiration time (as seen here https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-policies.html and https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PutParameter.html), but it seems there's no option for that with `put_parameter`. Is there an escape hatch I could use to pass the policy somehow today, or we would need to add policy support directly to `put_parameter` (I guess to `put_parameter_opts`)?

(sorry for using GH issues as a support forum, wasn't sure where else I could discuss this topic)

**Comment by gpedic** [comment]
Hey @sickill sorry for the late reply I hope you figured out the issue in the meantime.

You can modify the request operation data structure content however you like (in this case adding policies) before sending it off via `ExAws.request`, that's true for ex_aws operations in general 

```
ExAws.SSM.put_parameter(..)
|> custom_insert_policies(policies)
|> ExAws.request()
```

I will also look into adding support for that param

**Comment by ku1ik** [comment]
No worries! I haven't figured this out so far, so thanks for the tip!

Btw, many thanks for creating this library 👌
